const App = (props) => {
  const { notes } = props;

  return (
    <div>
      <h1>Notes</h1>
      <ul>
        <ul>
          {notes.map((note) => (
            <li key={note.id}>{note.content}</li>
          ))}
        </ul>
      </ul>
    </div>
  );
};

/*  The list items, i.e. the elements generated by the map method, must each have a unique key value: an attribute called key. */

/* React uses the key attributes of objects in an array to determine how to update the view generated by a component when the component is re-rendered. */

export default App;
